# Generated by Django 2.2 on 2020-04-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='customer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
