# Generated by Django 2.2 on 2020-05-08 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0017_auto_20200330_1436'),
        ('payments', '0002_payment_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='fund_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deposits.FundSource'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'SUBMITTED'), (1, 'PROCESSING'), (4, 'CANCELED'), (2, 'SUCCESS'), (3, 'FAILED')], default=0),
        ),
    ]
