# Generated by Django 2.2 on 2020-02-09 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_default_withdraw_beneficiary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='default_deposit_fund_source',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deposits.FundSource'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='default_withdraw_beneficiary',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='withdraws.Beneficiary'),
        ),
    ]
