# Generated by Django 2.2 on 2020-02-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200218_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_activated',
            field=models.BooleanField(default=False),
        ),
    ]
