# Generated by Django 2.2 on 2020-03-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_account_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_bank_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='account_number',
            field=models.CharField(blank=True, editable=False, max_length=15, null=True),
        ),
    ]
