# Generated by Django 2.2 on 2020-04-08 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_send_notifications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='updated_at',
            new_name='creat',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='created_at',
            new_name='updat',
        ),
    ]
