# Generated by Django 2.2 on 2020-04-08 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200408_0852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='creat',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='updat',
            new_name='updated_at',
        ),
    ]
