# Generated by Django 2.2 on 2020-07-24 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_massnotification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='massnotification',
            options={'verbose_name_plural': 'Mass Notification'},
        ),
    ]
