# Generated by Django 2.2 on 2020-07-24 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200724_1644'),
        ('users', '0014_auto_20200724_1040'),
    ]

    operations = [
    ]
