# Generated by Django 2.2 on 2020-08-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_merge_20200724_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='paid_referer_bonus',
            field=models.BooleanField(default=False),
        ),
    ]
