# Generated by Django 2.2 on 2020-02-12 12:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kyc_profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KYCProfiles',
            new_name='KYCProfile',
        ),
    ]
