# Generated by Django 2.2 on 2020-02-12 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_profiles', '0002_auto_20200212_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kycprofile',
            old_name='bvn_number',
            new_name='bvn',
        ),
    ]
