# Generated by Django 2.2 on 2020-02-12 15:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_profiles', '0003_auto_20200212_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
