# Generated by Django 2.2 on 2020-02-06 16:32

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_auto_20200206_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_deposit', models.PositiveSmallIntegerField(choices=[(1, 'AutoSave'), (0, 'QuickSave'), (2, 'ReferralBonus')], default=0)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'PROCESSING'), (3, 'CANCELED'), (1, 'SUCCESS'), (2, 'FAILED')], default=0)),
                ('reference', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
        ),
    ]
