# Generated by Django 2.2 on 2020-02-09 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0005_auto_20200208_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundsource',
            old_name='name',
            new_name='bank_name',
        ),
    ]
