# Generated by Django 2.2 on 2020-02-09 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0007_auto_20200209_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='subscription',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
