# Generated by Django 2.2 on 2020-02-09 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
        ('deposits', '0008_auto_20200209_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.Subscription'),
        ),
    ]
