# Generated by Django 2.2 on 2020-02-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0010_auto_20200209_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundsource',
            name='auth_code',
            field=models.CharField(max_length=50),
        ),
    ]
