# Generated by Django 2.2 on 2020-02-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0013_auto_20200209_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='type_of_deposit',
            field=models.PositiveSmallIntegerField(choices=[(1, 'AutoSave'), (0, 'QuickSave'), (2, 'ReferralBonus'), (3, 'TermDeposit')], default=0),
        ),
    ]
