# Generated by Django 2.2 on 2020-02-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0014_auto_20200209_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundsource',
            name='card_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fundsource',
            name='exp_month',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fundsource',
            name='exp_year',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fundsource',
            name='last4',
            field=models.CharField(max_length=50),
        ),
    ]
