# Generated by Django 2.2 on 2020-03-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0016_auto_20200218_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='type_of_deposit',
            field=models.PositiveSmallIntegerField(choices=[(1, 'AutoSave'), (0, 'QuickSave'), (2, 'ReferralBonus'), (3, 'TermDeposit'), (4, 'BankTransfer')], default=0),
        ),
    ]
