# Generated by Django 2.2 on 2020-02-06 14:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20200206_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type_of_account',
            field=models.PositiveSmallIntegerField(choices=[(0, 'WALLET'), (1, 'DIRECT'), (2, 'DEPOSIT')], editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('user', 'type_of_account')},
        ),
    ]
