# Generated by Django 2.2 on 2020-03-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200218_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_interest_withdrawal_day',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
