# Generated by Django 2.2 on 2020-06-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_account_last_interest_withdrawal_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type_of_account',
            field=models.PositiveSmallIntegerField(choices=[(0, 'WALLET'), (1, 'AUTOSAVE'), (2, 'TARGET')], editable=False),
        ),
    ]
