# Generated by Django 2.2 on 2020-06-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200609_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type_of_account',
            field=models.PositiveSmallIntegerField(choices=[(0, 'WALLET'), (1, 'DIRECT'), (2, 'DEPOSIT')], editable=False),
        ),
    ]
