# Generated by Django 2.2 on 2020-07-24 09:40

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200609_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='interest_for_today',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
