# Generated by Django 2.2 on 2020-07-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_auto_20200415_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='activated_users_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metric',
            name='autosave_wallet_transfer_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metric',
            name='autosave_wallet_transfer_sum',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='metric',
            name='interest_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metric',
            name='interest_sum',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='metric',
            name='payments_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metric',
            name='payments_sum',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='metric',
            name='target_wallet_transfer_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metric',
            name='target_wallet_transfer_sum',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='metric',
            name='wallet_autosave_transfer_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metric',
            name='wallet_autosave_transfer_sum',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='metric',
            name='wallet_target_transfer_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metric',
            name='wallet_target_transfer_sum',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='metric',
            name='wallet_wallet_transfer_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metric',
            name='wallet_wallet_transfer_sum',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
