# Generated by Django 2.2 on 2020-07-03 09:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_auto_20200702_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
