# Generated by Django 2.2 on 2020-07-24 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0004_auto_20200703_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metric',
            old_name='interest_count',
            new_name='total_accounts_with_interests',
        ),
        migrations.RenameField(
            model_name='metric',
            old_name='interest_sum',
            new_name='total_interests_volume',
        ),
        migrations.RenameField(
            model_name='metric',
            old_name='payments_count',
            new_name='total_payments',
        ),
        migrations.RenameField(
            model_name='metric',
            old_name='payments_sum',
            new_name='total_payments_volume',
        ),
    ]
