# Generated by Django 2.2 on 2020-07-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0005_auto_20200724_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='total_interests_for_today',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
