# Generated by Django 2.2 on 2020-07-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0006_metric_total_interests_for_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='autosave_breaking_fees_volume',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='metric',
            name='bill_payment_fees_volume',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
