# Generated by Django 2.2 on 2020-08-14 12:09

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0007_auto_20200724_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='airtime_bonus_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metric',
            name='airtime_bonus_volume',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='metric',
            name='referral_bonus_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metric',
            name='referral_bonus_volume',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='metric',
            name='total_chicken_change_deposits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metric',
            name='total_chicken_change_deposits_volume',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='metric',
            name='total_monnify_deposits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metric',
            name='total_monnify_deposits_volume',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='metric',
            name='total_paystack_deposits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metric',
            name='total_paystack_deposits_volume',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
