# Generated by Django 2.2 on 2020-05-12 08:35

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_account_last_interest_withdrawal_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_transaction', models.PositiveSmallIntegerField(choices=[(0, 'Deposit'), (1, 'Withdraw'), (2, 'Transfer'), (3, 'Payment')], default=0)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'SUBMITTED'), (1, 'PROCESSING'), (4, 'CANCELED'), (2, 'SUCCESS'), (3, 'FAILED')], default=0)),
                ('reference', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('balance_after_transaction', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('memo', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('src_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
        ),
    ]
