# Generated by Django 2.2 on 2020-05-12 08:38

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='data',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
