# Generated by Django 2.2 on 2020-05-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_auto_20200521_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type_of_transaction',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Deposit'), (1, 'Withdraw'), (2, 'Transfer'), (3, 'Payment'), (4, 'Interest')], default=0),
        ),
    ]
