# Generated by Django 2.2 on 2020-06-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_auto_20200526_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='memo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
