# Generated by Django 2.2 on 2020-08-11 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_transaction_total'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChickenChange',
        ),
    ]
