# Generated by Django 2.2 on 2020-02-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='reference',
            field=models.CharField(default='as', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
