# Generated by Django 2.2 on 2020-03-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0004_auto_20200209_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='transaction_description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='transfer_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'PeerToPeer'), (1, 'InternalTransfer'), (2, 'Interest'), (3, 'BillPayment'), (4, 'ReferralBonus')], default=0),
        ),
    ]
