# Generated by Django 2.2 on 2020-02-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
