# Generated by Django 2.2 on 2020-02-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20200209_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='previous_paydate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
