# Generated by Django 2.2 on 2020-02-09 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_auto_20200209_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='plan_code',
        ),
    ]
