# Generated by Django 2.2 on 2020-02-09 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_remove_subscription_plan_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='fund_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deposits.FundSource'),
        ),
    ]
