# Generated by Django 2.2 on 2020-02-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_auto_20200209_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='next_paydate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
