# Generated by Django 2.2 on 2020-02-18 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_subscription_next_paydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
    ]
