# Generated by Django 2.2 on 2020-02-08 13:02

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_remove_account_default_deposit_fund_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=50, null=True)),
                ('uid2', models.CharField(blank=True, max_length=50, null=True)),
                ('type_of_deposit', models.PositiveSmallIntegerField(choices=[(0, 'SavestUser'), (1, 'BankAccount')], default=1)),
                ('recipient_code', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('recipient_name', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'PROCESSING'), (3, 'CANCELED'), (1, 'SUCCESS'), (2, 'FAILED')], default=0)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='withdraws.Beneficiary')),
            ],
        ),
    ]
