# Generated by Django 2.2 on 2020-02-08 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('withdraws', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='beneficiary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='withdraws.Beneficiary'),
        ),
    ]
