# Generated by Django 2.2 on 2020-02-09 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('withdraws', '0005_auto_20200209_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='beneficiary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='withdraws.Beneficiary'),
        ),
    ]
