# Generated by Django 2.2 on 2020-02-18 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('withdraws', '0007_auto_20200209_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
    ]
