# Generated by Django 2.2 on 2020-04-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdraws', '0008_auto_20200218_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'SUBMITTED'), (1, 'PROCESSING'), (4, 'CANCELED'), (2, 'SUCCESS'), (3, 'FAILED')], default=0),
        ),
    ]
