# Generated by Django 2.2 on 2020-02-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safelocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='safelock',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
