# Generated by Django 2.2 on 2020-03-30 13:36

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safelocks', '0003_auto_20200218_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='safelock',
            name='interest',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
