# Generated by Django 2.2 on 2020-05-26 11:14

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_auto_20200218_1053'),
        ('safelocks', '0004_safelock_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='safelock',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Rent/Accomodation'), (1, 'Travel'), (2, 'Car'), (3, 'Fees'), (4, 'Education'), (5, 'Business'), (6, 'Event'), (7, 'Gadget'), (8, 'Birthday'), (9, 'Investment'), (10, 'LifeGoals'), (11, 'Other')], default=11),
        ),
        migrations.AddField(
            model_name='safelock',
            name='subscription',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.Subscription'),
        ),
        migrations.AddField(
            model_name='safelock',
            name='target_goal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
